using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Platform;
using SDB;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace StS_GUI_Avalonia
{
    public partial class MainWindow : Window
    {
        private SchulDB myschool;
        private List<ListBoxItem> leftItems = new();
        private List<ListBoxItem> rightItems = new();
        private SaveFileDialog sfd;
        private OpenFileDialog ofd;
        //autogenerated fields
        private MenuItem guimnuSchuleLaden;
        private MenuItem guimnuSchuleSpeichern;
        private MenuItem guimnuSchuleSpeichernUnter;
        private MenuItem guimnuSchuleVersSpeichern;
        private MenuItem guimnuVersSchuleLaden;
        private MenuItem guimnuExit;
        private MenuItem guimnuLoadFolder;
        private MenuItem guimnuLoadSuSFromFile;
        private MenuItem guimnuLoadLuLFromFile;
        private MenuItem guimnuLoadKurseFromFile;
        private MenuItem guimnuLoadUsernamesMail;
        private MenuItem guimnuLoadZweitaccounts;
        private MenuItem guimnuReadDiffs;
        private MenuItem guimnuExportToCSV;
        private MenuItem guimnuAbout;
        private TextBox guitbLeftSearch;
        private ListBox guiLeftListBox;
        private TextBox guitbRightSearch;
        private ListBox guiRightListBox;
        private TextBox guitbSuSID;
        private TextBox guitbSuSVorname;
        private TextBox guitbSuSnachname;
        private TextBox guitbSuSElternadresse;
        private TextBox guitbSuSAIXMail;
        private TextBox guitbSuSNutzername;
        private TextBox guitbSuSKurse;
        private CheckBox guicbSuSZweitaccount;
        private Button guibtnSuSAdd;
        private Button guibtnSuSDel;
        private TextBox guitbLuLID;
        private TextBox guitbLuLVorname;
        private TextBox guitbLuLnachname;
        private TextBox guitbLuLKuerzel;
        private TextBox guitbLuLFach;
        private TextBox guitbLuLMail;
        private TextBox guitbLuLtmpPwd;
        private TextBox guitbLuLKurse;
        private Button guibtnLuLAdd;
        private Button guibtnLuLDel;
        private TextBox guitbKursbezeichnung;
        private TextBox guitbKursLuL;
        private TextBox guitbKursFach;
        private TextBox guitbKursSuffix;
        private TextBox guitbKursKlasse;
        private TextBox guitbKursStufe;
        private CheckBox guicbKursIstKurs;
        private CheckBox guicbKursMarkierteSuSEinschreiben;
        private CheckBox guicbKursSuSdKlasseEinschreiben;
        private CheckBox guicbKursSuSdStufeEinschreiben;
        private Button guibtnKurseAdd;
        private Button guibtnKurseDel;
        private CheckBox guicbSuS;
        private CheckBox guicbLuL;
        private CheckBox guicbKurs;
        private CheckBox guicbEltern;
        private CheckBox guicbMoodle;
        private CheckBox guicbAIX;
        private CheckBox guicbLog;
        private CheckBox guicbExportwithPasswort;
        private Button guibtnExport;
        private TextBox guitbExportKl;
        private TextBox guitbExportF;
        private CheckBox guicbExportVorlagenkurse;
        private TextBox guitbExportStufenkurse;
        private CheckBox guicbExportStufen;
        private Button guibtnExportStufenkurs;
        private CheckBox guicbFehlerSuSoK;
        private CheckBox guicbFehlerLuLoK;
        private CheckBox guicbFehlerLeereKurse;
        private CheckBox guicbFehlerSuS;
        private CheckBox guicbFehlerLuL;
        private CheckBox guicbFehlerKurse;
        private Button guibtnFehlerSuche;
        private Button guibtnFehlerExport;
        private ListBox guilbFehlerliste;
        private TextBox guitbSettingMailplatzhalter;
        private TextBox guitbSettingKurssuffix;
        private TextBox guitbSettingKursersetzung;
        private ListBox guilbSettingFachkurz;
        private ListBox guilbSettingFachlang;
        private Button guibtnSettingSave;
        private DataGrid guilogDataGrid;
        public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
            for (int i = 0; i < 1000; i++)
            {
                leftItems.Add(new ListBoxItem { Content = "Links" + i });
                rightItems.Add(new ListBoxItem { Content = "Rechts" + i });
            }
            myschool = new SchulDB(":memory:");
            sfd = new SaveFileDialog();
            ofd = new OpenFileDialog
            {
                AllowMultiple = false
            };
            var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
            if (assets != null)
            {
                this.Icon = new WindowIcon(assets.Open(new Uri("avares://StS-GUI-Avalonia/gfx/school-building.ico")));
            }
            //GUI und Methoden verknüpfen
            guimnuSchuleLaden = this.FindControl<MenuItem>("mnuSchuleLaden");
            guimnuSchuleSpeichern = this.FindControl<MenuItem>("mnuSchuleSpeichern");
            guimnuSchuleSpeichernUnter = this.FindControl<MenuItem>("mnuSchuleSpeichernUnter");
            guimnuSchuleVersSpeichern = this.FindControl<MenuItem>("mnuSchuleVersSpeichern");
            guimnuVersSchuleLaden = this.FindControl<MenuItem>("mnuVersSchuleLaden");
            guimnuExit = this.FindControl<MenuItem>("mnuExit");
            guimnuLoadFolder = this.FindControl<MenuItem>("mnuLoadFolder");
            guimnuLoadSuSFromFile = this.FindControl<MenuItem>("mnuLoadSuSFromFile");
            guimnuLoadLuLFromFile = this.FindControl<MenuItem>("mnuLoadLuLFromFile");
            guimnuLoadKurseFromFile = this.FindControl<MenuItem>("mnuLoadKurseFromFile");
            guimnuLoadUsernamesMail = this.FindControl<MenuItem>("mnuLoadUsernamesMail");
            guimnuLoadZweitaccounts = this.FindControl<MenuItem>("mnuLoadZweitaccounts");
            guimnuReadDiffs = this.FindControl<MenuItem>("mnuReadDiffs");
            guimnuExportToCSV = this.FindControl<MenuItem>("mnuExportToCSV");
            guimnuAbout = this.FindControl<MenuItem>("mnuAbout");
            guitbLeftSearch = this.FindControl<TextBox>("tbLeftSearch");
            guiLeftListBox = this.FindControl<ListBox>("LeftListBox");
            guitbRightSearch = this.FindControl<TextBox>("tbRightSearch");
            guiRightListBox = this.FindControl<ListBox>("RightListBox");
            guitbSuSID = this.FindControl<TextBox>("tbSuSID");
            guitbSuSVorname = this.FindControl<TextBox>("tbSuSVorname");
            guitbSuSnachname = this.FindControl<TextBox>("tbSuSnachname");
            guitbSuSElternadresse = this.FindControl<TextBox>("tbSuSElternadresse");
            guitbSuSAIXMail = this.FindControl<TextBox>("tbSuSAIXMail");
            guitbSuSNutzername = this.FindControl<TextBox>("tbSuSNutzername");
            guitbSuSKurse = this.FindControl<TextBox>("tbSuSKurse");
            guicbSuSZweitaccount = this.FindControl<CheckBox>("cbSuSZweitaccount");
            guibtnSuSAdd = this.FindControl<Button>("btnSuSAdd");
            guibtnSuSDel = this.FindControl<Button>("btnSuSDel");
            guitbLuLID = this.FindControl<TextBox>("tbLuLID");
            guitbLuLVorname = this.FindControl<TextBox>("tbLuLVorname");
            guitbLuLnachname = this.FindControl<TextBox>("tbLuLnachname");
            guitbLuLKuerzel = this.FindControl<TextBox>("tbLuLKuerzel");
            guitbLuLFach = this.FindControl<TextBox>("tbLuLFach");
            guitbLuLMail = this.FindControl<TextBox>("tbLuLMail");
            guitbLuLtmpPwd = this.FindControl<TextBox>("tbLuLtmpPwd");
            guitbLuLKurse = this.FindControl<TextBox>("tbLuLKurse");
            guibtnLuLAdd = this.FindControl<Button>("btnLuLAdd");
            guibtnLuLDel = this.FindControl<Button>("btnLuLDel");
            guitbKursbezeichnung = this.FindControl<TextBox>("tbKursbezeichnung");
            guitbKursLuL = this.FindControl<TextBox>("tbKursLuL");
            guitbKursFach = this.FindControl<TextBox>("tbKursFach");
            guitbKursSuffix = this.FindControl<TextBox>("tbKursSuffix");
            guitbKursKlasse = this.FindControl<TextBox>("tbKursKlasse");
            guitbKursStufe = this.FindControl<TextBox>("tbKursStufe");
            guicbKursIstKurs = this.FindControl<CheckBox>("cbKursIstKurs");
            guicbKursMarkierteSuSEinschreiben = this.FindControl<CheckBox>("cbKursMarkierteSuSEinschreiben");
            guicbKursSuSdKlasseEinschreiben = this.FindControl<CheckBox>("cbKursSuSdKlasseEinschreiben");
            guicbKursSuSdStufeEinschreiben = this.FindControl<CheckBox>("cbKursSuSdStufeEinschreiben");
            guibtnKurseAdd = this.FindControl<Button>("btnKurseAdd");
            guibtnKurseDel = this.FindControl<Button>("btnKurseDel");
            guicbSuS = this.FindControl<CheckBox>("cbSuS");
            guicbLuL = this.FindControl<CheckBox>("cbLuL");
            guicbKurs = this.FindControl<CheckBox>("cbKurs");
            guicbEltern = this.FindControl<CheckBox>("cbEltern");
            guicbMoodle = this.FindControl<CheckBox>("cbMoodle");
            guicbAIX = this.FindControl<CheckBox>("cbAIX");
            guicbLog = this.FindControl<CheckBox>("cbLog");
            guicbExportwithPasswort = this.FindControl<CheckBox>("cbExportwithPasswort");
            guibtnExport = this.FindControl<Button>("btnExport");
            guitbExportKl = this.FindControl<TextBox>("tbExportKl");
            guitbExportF = this.FindControl<TextBox>("tbExportF");
            guicbExportVorlagenkurse = this.FindControl<CheckBox>("cbExportVorlagenkurse");
            guitbExportStufenkurse = this.FindControl<TextBox>("tbExportStufenkurse");
            guicbExportStufen = this.FindControl<CheckBox>("cbExportStufen");
            guibtnExportStufenkurs = this.FindControl<Button>("btnExportStufenkurs");
            guicbFehlerSuSoK = this.FindControl<CheckBox>("cbFehlerSuSoK");
            guicbFehlerLuLoK = this.FindControl<CheckBox>("cbFehlerLuLoK");
            guicbFehlerLeereKurse = this.FindControl<CheckBox>("cbFehlerLeereKurse");
            guicbFehlerSuS = this.FindControl<CheckBox>("cbFehlerSuS");
            guicbFehlerLuL = this.FindControl<CheckBox>("cbFehlerLuL");
            guicbFehlerKurse = this.FindControl<CheckBox>("cbFehlerKurse");
            guibtnFehlerSuche = this.FindControl<Button>("btnFehlerSuche");
            guibtnFehlerExport = this.FindControl<Button>("btnFehlerExport");
            guilbFehlerliste = this.FindControl<ListBox>("lbFehlerliste");
            guitbSettingMailplatzhalter = this.FindControl<TextBox>("tbSettingMailplatzhalter");
            guitbSettingKurssuffix = this.FindControl<TextBox>("tbSettingKurssuffix");
            guitbSettingKursersetzung = this.FindControl<TextBox>("tbSettingKursersetzung");
            guilbSettingFachkurz = this.FindControl<ListBox>("lbSettingFachkurz");
            guilbSettingFachlang = this.FindControl<ListBox>("lbSettingFachlang");
            guibtnSettingSave = this.FindControl<Button>("btnSettingSave");
            guilogDataGrid = this.FindControl<DataGrid>("logDataGrid");


            this.FindControl<MenuItem>("mnuSchuleLaden").Click += OnMnuSchoolLoadClick;
            this.FindControl<MenuItem>("mnuSchuleSpeichern").Click += OnMnuschulespeichernClick;
            this.FindControl<MenuItem>("mnuSchuleSpeichernUnter").Click += OnMnuschulespeichernunterClick;
            this.FindControl<MenuItem>("mnuSchuleVersSpeichern").Click += OnMnuschuleversspeichernClick;
            this.FindControl<MenuItem>("mnuVersSchuleLaden").Click += OnMnuversschuleladenClick;
            this.FindControl<MenuItem>("mnuExit").Click += OnMnuexitClick;
            this.FindControl<MenuItem>("mnuLoadFolder").Click += OnMnuloadfolderClick;
            this.FindControl<MenuItem>("mnuLoadSuSFromFile").Click += OnMnuloadsusfromfileClick;
            this.FindControl<MenuItem>("mnuLoadLuLFromFile").Click += OnMnuloadlulfromfileClick;
            this.FindControl<MenuItem>("mnuLoadKurseFromFile").Click += OnMnuloadkursefromfileClick;
            this.FindControl<MenuItem>("mnuLoadUsernamesMail").Click += OnMnuloadusernamesmailClick;
            this.FindControl<MenuItem>("mnuLoadZweitaccounts").Click += OnMnuloadzweitaccountsClick;
            this.FindControl<MenuItem>("mnuReadDiffs").Click += OnMnureaddiffsClick;
            this.FindControl<MenuItem>("mnuExportToCSV").Click += OnMnuexporttocsvClick;
            this.FindControl<MenuItem>("mnuAbout").Click += OnMnuaboutClick;
            this.FindControl<ComboBox>("cboxDataLeft").KeyUp += OnCbleftClick;
            this.FindControl<TextBox>("tbLeftSearch").KeyUp += OnTbleftsearchClick;
            this.FindControl<ComboBox>("cboxDataRigth").KeyUp += OnCbrightClick;
            this.FindControl<TextBox>("tbRightSearch").KeyUp += OnTbrightsearchClick;
            this.FindControl<TextBox>("tbSuSID").KeyUp += OnTbsusidClick;
            this.FindControl<TextBox>("tbSuSVorname").KeyUp += OnTbsusvornameClick;
            this.FindControl<TextBox>("tbSuSnachname").KeyUp += OnTbsusnachnameClick;
            this.FindControl<TextBox>("tbSuSElternadresse").KeyUp += OnTbsuselternadresseClick;
            this.FindControl<TextBox>("tbSuSAIXMail").KeyUp += OnTbsusaixmailClick;
            this.FindControl<TextBox>("tbSuSNutzername").KeyUp += OnTbsusnutzernameClick;
            this.FindControl<TextBox>("tbSuSKurse").KeyUp += OnTbsuskurseClick;
            this.FindControl<CheckBox>("cbSuSZweitaccount").Click += OnCbSuSZweitaccountClick;
            this.FindControl<Button>("btnSuSAdd").Click += OnBtnsusaddClick;
            this.FindControl<Button>("btnSuSDel").Click += OnBtnsusdelClick;
            this.FindControl<TextBox>("tbLuLID").KeyUp += OnTblulidClick;
            this.FindControl<TextBox>("tbLuLVorname").KeyUp += OnTblulvornameClick;
            this.FindControl<TextBox>("tbLuLnachname").KeyUp += OnTblulnachnameClick;
            this.FindControl<TextBox>("tbLuLKuerzel").KeyUp += OnTblulkuerzelClick;
            this.FindControl<TextBox>("tbLuLFach").KeyUp += OnTblulfachClick;
            this.FindControl<TextBox>("tbLuLMail").KeyUp += OnTblulmailClick;
            this.FindControl<TextBox>("tbLuLtmpPwd").KeyUp += OnTblultmppwdClick;
            this.FindControl<TextBox>("tbLuLKurse").KeyUp += OnTblulkurseClick;
            this.FindControl<Button>("btnLuLAdd").Click += OnBtnluladdClick;
            this.FindControl<Button>("btnLuLDel").Click += OnBtnluldelClick;
            this.FindControl<TextBox>("tbKursbezeichnung").KeyUp += OnTbkursbezeichnungClick;
            this.FindControl<TextBox>("tbKursLuL").KeyUp += OnTbkurslulClick;
            this.FindControl<TextBox>("tbKursFach").KeyUp += OnTbkursfachClick;
            this.FindControl<TextBox>("tbKursSuffix").KeyUp += OnTbkurssuffixClick;
            this.FindControl<TextBox>("tbKursKlasse").KeyUp += OnTbkursklasseClick;
            this.FindControl<TextBox>("tbKursStufe").KeyUp += OnTbkursstufeClick;
            this.FindControl<CheckBox>("cbKursIstKurs").Click += OnCbkursistkursClick;
            this.FindControl<CheckBox>("cbKursMarkierteSuSEinschreiben").Click += OnCbkursmarkiertesuseinschreibenClick;
            this.FindControl<CheckBox>("cbKursSuSdKlasseEinschreiben").Click += OnCbkurssusdklasseeinschreibenClick;
            this.FindControl<CheckBox>("cbKursSuSdStufeEinschreiben").Click += OnCbkurssusdstufeeinschreibenClick;
            this.FindControl<Button>("btnKurseAdd").Click += OnBtnkurseaddClick;
            this.FindControl<Button>("btnKurseDel").Click += OnBtnkursedelClick;
            this.FindControl<CheckBox>("cbSuS").Click += OnCbsusClick;
            this.FindControl<CheckBox>("cbLuL").Click += OnCblulClick;
            this.FindControl<CheckBox>("cbKurs").Click += OnCbkursClick;
            this.FindControl<CheckBox>("cbEltern").Click += OnCbelternClick;
            this.FindControl<CheckBox>("cbMoodle").Click += OnCbmoodleClick;
            this.FindControl<CheckBox>("cbAIX").Click += OnCbaixClick;
            this.FindControl<CheckBox>("cbLog").Click += OnCblogClick;
            this.FindControl<CheckBox>("cbExportwithPasswort").Click += OnCbexportwithpasswortClick;
            this.FindControl<Button>("btnExport").Click += OnBtnexportClick;
            this.FindControl<TextBox>("tbExportKl").KeyUp += OnTbexportklClick;
            this.FindControl<TextBox>("tbExportF").KeyUp += OnTbexportfClick;
            this.FindControl<CheckBox>("cbExportVorlagenkurse").Click += OnCbexportvorlagenkurseClick;
            this.FindControl<TextBox>("tbExportStufenkurse").KeyUp += OnTbexportstufenkurseClick;
            this.FindControl<CheckBox>("cbExportStufen").Click += OnCbexportstufenClick;
            this.FindControl<Button>("btnExportStufenkurs").Click += OnBtnexportstufenkursClick;
            this.FindControl<CheckBox>("cbFehlerSuSoK").Click += OnCbfehlersusokClick;
            this.FindControl<CheckBox>("cbFehlerLuLoK").Click += OnCbfehlerlulokClick;
            this.FindControl<CheckBox>("cbFehlerLeereKurse").Click += OnCbfehlerleerekurseClick;
            this.FindControl<CheckBox>("cbFehlerSuS").Click += OnCbfehlersusClick;
            this.FindControl<CheckBox>("cbFehlerLuL").Click += OnCbfehlerlulClick;
            this.FindControl<CheckBox>("cbFehlerKurse").Click += OnCbfehlerkurseClick;
            this.FindControl<Button>("btnFehlerSuche").Click += OnBtnfehlersucheClick;
            this.FindControl<Button>("btnFehlerExport").Click += OnBtnfehlerexportClick;
            this.FindControl<ListBox>("lbFehlerliste").KeyUp += OnTbfehlerlisteClick;
            this.FindControl<TextBox>("tbSettingMailplatzhalter").KeyUp += OnTbsettingmailplatzhalterClick;
            this.FindControl<TextBox>("tbSettingKurssuffix").KeyUp += OnTbsettingkurssuffixClick;
            this.FindControl<TextBox>("tbSettingKursersetzung").KeyUp += OnTbsettingkursersetzungClick;
            this.FindControl<ListBox>("lbSettingFachkurz").KeyUp += OnTbsettingfachkurzClick;
            this.FindControl<ListBox>("lbSettingFachlang").KeyUp += OnTbsettingfachlangClick;
            this.FindControl<Button>("btnSettingSave").Click += OnBtnsettingsaveClick;
            this.FindControl<ListBox>("LeftListBox").Items = leftItems;
            this.FindControl<ListBox>("LeftListBox").SelectionMode = SelectionMode.Multiple;
            this.FindControl<ListBox>("LeftListBox").SelectionChanged += OnLeftlistboxSelectionChanged;
            this.FindControl<ListBox>("RightListBox").Items = rightItems;
            this.FindControl<ListBox>("RightListBox").SelectionMode = SelectionMode.Multiple;
            this.FindControl<ListBox>("RightListBox").SelectionChanged += OnRigthlistboxSelectionChanged;
        }



        private void SetupSaveDialog(SaveFileDialog sfd, string dialogtitle, string[] extensions, string[] extensionsanames)
        {
            if (extensions.Length == extensionsanames.Length)
            {
                sfd.DefaultExtension = extensions[0];
                sfd.Title = dialogtitle;
                List<FileDialogFilter> Filters = new();
                for (int i = 0; i < extensions.Length; i++)
                {
                    FileDialogFilter filter = new();
                    List<string> extension = new();
                    extension.Add(extensions[i]);
                    filter.Extensions = extension;
                    filter.Name = extensionsanames[i];
                    Filters.Add(filter);
                }
                sfd.Filters = Filters;
            }
        }

        private void SetupOpenDialog(OpenFileDialog ofd, string dialogtitle, string[] extensions, string[] extensionsanames)
        {
            if (extensions.Length == extensionsanames.Length)
            {
                ofd.Title = dialogtitle;
                List<FileDialogFilter> Filters = new();
                for (int i = 0; i < extensions.Length; i++)
                {
                    FileDialogFilter filter = new();
                    List<string> extension = new();
                    extension.Add(extensions[i]);
                    filter.Extensions = extension;
                    filter.Name = extensionsanames[i];
                    Filters.Add(filter);
                }
                ofd.Filters = Filters;
            }
        }


        private void OnLeftlistboxSelectionChanged(object? sender, SelectionChangedEventArgs e)
        {
            if (sender != null && sender.GetType().Equals(this.FindControl<ListBox>("LeftListBox")))
            {
                var leftbox = (ListBox)sender;
                Debug.WriteLine(leftbox.SelectedItems.Count);

            }
        }

        private void OnRigthlistboxSelectionChanged(object? sender, SelectionChangedEventArgs e)
        {
            if (sender != null && sender.GetType().Equals(this.FindControl<ListBox>("RightListBox")))
            {
                var rightbox = (ListBox)sender;
                Debug.WriteLine(rightbox.SelectedItems.Count);
            }
        }

        public async void OnMnuSchoolLoadClick(object? sender, RoutedEventArgs e)
        {
            SetupOpenDialog(ofd, "Lade Datenbankdatei", new String[] { "sqlite" }, new String[] { "Datenbankdatei" });

            var SettingsFileName = await ofd.ShowAsync(this);
            if(SettingsFileName != null && SettingsFileName.Length > 0)
            {
                var tbSetMail = this.FindControl<TextBox>("tbSettingMailplatzhalter");
                var tbFachErs = this.FindControl<TextBox>("tbSettingKursersetzung");
                var tbKurssuffix = this.FindControl<TextBox>("tbSettingKurssuffix");
                myschool = new SchulDB(SettingsFileName[0]);
                LoadTypData();
                List<string> settings = myschool.GetSettings();
                if (settings.Count == 3)
                {
                    foreach (string sett in settings)
                    {
                        string[] s = sett.Split(';');
                        if (s[0].Equals("mailsuffix"))
                        {
                            tbSetMail.Text = s[1];
                        }
                        else if (s[0].Equals("fachersetzung"))
                        {
                            tbFachErs.Text = s[1];
                        }
                        else if (s[0].Equals("kurssuffix"))
                        {
                            tbKurssuffix.Text = s[1];
                        }
                    }
                }
                SucheInhalt();
            }
            Debug.WriteLine(SettingsFileName[0]);
        }
        private void SucheInhalt()
        {
            try
            {
                var lbInhalt = this.FindControl<ListBox>("RightListBox");
                IoadInhaltData();
                List<string> tlist = new();
                foreach (string searchitem in guitbLeftSearch.Text.ToLower().Split(';'))
                {
                    foreach (string s in lbInhalt.Items)
                    {
                        if (s.ToLower().Contains(searchitem))
                        {
                            tlist.Add(s);
                        }
                    }
                }
                leftItems.Clear();
                foreach (string k in tlist)
                {
                    leftItems.Add(new ListBoxItem { Content = k });
                }
                //suchinhalttimer.Stop();
                //suchinhalttimer.Enabled = false;
            }
            catch (Exception ex)
            {
#if DEBUG
                myschool.AddLogMessage("Debug", ex.StackTrace + ";" + ex.Message);
#endif
                myschool.AddLogMessage("Fehler", "Fehler beim suchen in der Datenbank " + ex.Message);
            }
        }
        private void LoadTypData()
        {
            if (myschool != null)
            {
                if (this.FindControl<ComboBox>("cboxDataLeft").SelectedIndex == 0) //kurse
                {
                    //lLGInternToolStripMenuItem.Visible = false;
                    //elternAccountsMitexportierenToolStripMenuItem.Visible = true;
                    //mnuSuSKurs.Visible = true;
                    //mnuGenPwd.Visible = false;
                    //mnuSerienbrief.Visible = false;
                    leftItems.Clear();
                    foreach (string k in myschool.GetKursListe())
                    {
                        leftItems.Add(new ListBoxItem { Content = k.Split(';')[0]});
                    }
                }
                else if (this.FindControl<ComboBox>("cboxDataLeft").SelectedIndex == 1)//sus
                {
                    //lLGInternToolStripMenuItem.Visible = false;
                    //elternAccountsMitexportierenToolStripMenuItem.Visible = true;
                    //mnuSuSKurs.Visible = true;
                    //mnuGenPwd.Visible = false;
                    //mnuSerienbrief.Visible = true;
                    leftItems.Clear();
                    foreach (string s in myschool.GetSchuelerListe())
                    {
                        leftItems.Add(new ListBoxItem { Content = s.Split(';')[1] + ", " + s.Split(';')[2] + "; " + s.Split(';')[0] }); 
                    }
                }
                else if (this.FindControl<ComboBox>("cboxDataLeft").SelectedIndex == 2)//lul
                {
                    //lLGInternToolStripMenuItem.Visible = true;
                    //elternAccountsMitexportierenToolStripMenuItem.Visible = false;
                    //mnuSuSKurs.Visible = false;
                    //mnuGenPwd.Visible = true;
                    //mnuSerienbrief.Visible = false;
                    leftItems.Clear();
                    foreach (string l in myschool.GetLehrerListe())
                    {
                        leftItems.Add(new ListBoxItem { Content = l.Split(';')[4].ToUpper() + "; " + l.Split(';')[1] + ", " + l.Split(';')[2] });
                    }
                }
            }
            try
            {

            }
            catch (Exception ex)
            {
#if DEBUG
                myschool.AddLogMessage("Debug", ex.StackTrace + ";" + ex.Message);
#endif
                myschool.AddLogMessage("Fehler", "Fehler beim laden und anzeigen der Daten " + ex.Message);
            }
        }

        private void IoadInhaltData()
        {
            try
            {
                //lulv.Text = "";
                //luln.Text = "";
                //lulid.Text = "";
                //lulkrz.Text = "";
                //lulmail.Text = "";
                //lulfak.Text = "";
                //lulkurse.Text = "";
                //lulpwemp.Text = "";
                //susv.Text = "";
                //susn.Text = "";
                //susid.Text = "";
                //susmail.Text = "";
                //susklasse.Text = "";
                //sususer.Text = "";
                //tbsusaixmail.Text = "";
                //tbsuszweitmail.Text = "";
                //tbextrakurse.Text = "";
                //if (cbInhalt.SelectedIndex > -1 && lbTyp.Items.Count > 0 && cbInhalt.SelectedIndex != cbTyp.SelectedIndex && lbTyp.SelectedItems.Count > 0)
                //{
                //    if (cbTyp.SelectedIndex == 0)//Kurse -> Teilnehmer ausgeben
                //    {
                //        lbInhalt.Items.Clear();
                //        string k = myschool.GetKurs(lbTyp.SelectedItem.ToString());
                //        foreach (int susid in myschool.GetSuSAusKurs(k.Split(';')[0]))
                //        {
                //            string[] s = myschool.GetSchueler(susid).Split(';');
                //            lbInhalt.Items.Add(s[0] + "; " + s[1] + ", " + s[2]);
                //        }
                //        foreach (int lid in myschool.GetLuLAusKurs(k.Split(';')[0]))
                //        {
                //            string[] l = myschool.GetLehrer(lid).Split(';');
                //            lbInhalt.Items.Add(l[4].ToUpper() + "; " + l[1] + ", " + l[2]);
                //        }
                //        LoadKursData(lbTyp);
                //    }
                //    else if (cbTyp.SelectedIndex == 1 && cbInhalt.SelectedIndex == 0) //SuS + Kurse
                //    {
                //        lbInhalt.Items.Clear();
                //        int susid = Convert.ToInt32(lbTyp.SelectedItem.ToString().Split(';')[1].Trim());
                //        if (myschool.GetSchueler(susid) != null)
                //        {
                //            foreach (string k in myschool.GetKursVonSuS(susid))
                //            {
                //                lbInhalt.Items.Add(k);
                //            }
                //        }
                //        LoadUserData(susid);
                //    }
                //    else if (cbTyp.SelectedIndex == 1 && cbInhalt.SelectedIndex == 2)//sus + LuL
                //    {
                //        lbInhalt.Items.Clear();
                //        int susid = Convert.ToInt32(lbTyp.SelectedItem.ToString().Split(';')[1].Trim());
                //        List<int> llist = myschool.GetLuLvonSuS(susid).Distinct().ToList();
                //        if (myschool.GetLuLvonSuS(susid) != null)
                //        {
                //            //KL-Kurs ausfiltern?
                //            foreach (int lul in llist)
                //            {
                //                string[] l = myschool.GetLehrer(lul).Split(';');
                //                if (lbInhalt.Items.IndexOf(l[4].ToUpper() + "; " + l[1] + ", " + l[2]) == -1)
                //                {
                //                    lbInhalt.Items.Add(l[4].ToUpper() + "; " + l[1] + ", " + l[2]);
                //                }
                //            }
                //        }
                //        LoadUserData(susid);
                //    }
                //    else if (cbTyp.SelectedIndex == 2 && cbInhalt.SelectedIndex == 0)//LuL und Kurse
                //    {
                //        lbInhalt.Items.Clear();
                //        string l = myschool.GetLehrer(lbTyp.SelectedItem.ToString().Split(';')[0].Trim());
                //        int lulid = Convert.ToInt32(l.Split(';')[0]);
                //        List<string> llist = myschool.GetKursVonLuL(lulid);
                //        if (llist != null)
                //        {
                //            foreach (string k in llist)
                //            {
                //                lbInhalt.Items.Add(k.Split(';')[0]);
                //            }
                //            LoadUserData(lulid);
                //        }
                //    }
                //    else if (cbTyp.SelectedIndex == 2 && cbInhalt.SelectedIndex == 1)//LuL und SuS
                //    {
                //        lbInhalt.Items.Clear();
                //        string l = myschool.GetLehrer(lbTyp.SelectedItem.ToString().Split(';')[0].Trim());
                //        int lulid = Convert.ToInt32(l.Split(';')[0]);
                //        List<int> llist = myschool.GetSuSVonLuL(lulid);
                //        if (llist != null)
                //        {
                //            foreach (int sus in llist)
                //            {
                //                string[] s = myschool.GetSchueler(sus).Split(';');
                //                if (lbInhalt.Items.IndexOf(s[0] + "; " + s[1] + ", " + s[2]) == -1)
                //                {
                //                    lbInhalt.Items.Add(s[0] + "; " + s[1] + ", " + s[2]);
                //                }
                //            }
                //        }
                //        LoadUserData(lulid);
                //    }
                //}
                //else
                //{
                //    cbInhalt.SelectedIndex = (cbTyp.SelectedIndex + 1) % 3;
                //}
                //lbInhalt.Sorted = true;
            }
            catch (Exception ex)
            {
#if DEBUG
                myschool.AddLogMessage("Debug", ex.StackTrace + ";" + ex.Message);
#endif
                myschool.AddLogMessage("Fehler", "Fehler beim laden und anzeigen der Daten " + ex.Message);
            }
        }

        public void OnMnuschulespeichernClick(object? sender, RoutedEventArgs e)
        {
        }
        public async void OnMnuschulespeichernunterClick(object? sender, RoutedEventArgs e)
        {
            SetupSaveDialog(sfd, "Lade Datenbankdatei", new String[] { "sqlite" }, new String[] { "Datenbankdatei" });

            var SettingsFileName = await sfd.ShowAsync(this);
            Debug.WriteLine(SettingsFileName);
        }
        public void OnMnuschuleversspeichernClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuversschuleladenClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuexitClick(object? sender, RoutedEventArgs e)
        {
            this.Close();
        }
        public void OnMnuloadfolderClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuloadsusfromfileClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuloadlulfromfileClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuloadkursefromfileClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuloadusernamesmailClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuloadzweitaccountsClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnureaddiffsClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnMnuexporttocsvClick(object? sender, RoutedEventArgs e)
        {
        }
       
        public void OnMnuaboutClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbleftClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbleftsearchClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCboxdataleftClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbrightClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbrightsearchClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCboxdatarigthClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsusidClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsusvornameClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsusnachnameClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsuselternadresseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsusaixmailClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsusnutzernameClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsuskurseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnsusaddClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnsusdelClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblulidClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblulvornameClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblulnachnameClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblulkuerzelClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblulfachClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblulmailClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblultmppwdClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTblulkurseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnluladdClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnluldelClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbkursbezeichnungClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbkurslulClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbkursfachClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbkurssuffixClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbkursklasseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbkursstufeClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbkursistkursClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbkursmarkiertesuseinschreibenClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbkurssusdklasseeinschreibenClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbkurssusdstufeeinschreibenClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnkurseaddClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnkursedelClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbsusClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCblulClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbkursClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbelternClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbmoodleClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbaixClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCblogClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbexportwithpasswortClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnexportClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbexportklClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbexportfClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbexportvorlagenkurseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbexportstufenkurseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbexportstufenClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnexportstufenkursClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbfehlersusokClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbfehlerlulokClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbfehlerleerekurseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbfehlersusClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbfehlerlulClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbfehlerkurseClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnfehlersucheClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnfehlerexportClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbfehlerlisteClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsettingmailplatzhalterClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsettingkurssuffixClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsettingkursersetzungClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsettingfachkurzClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnTbsettingfachlangClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnBtnsettingsaveClick(object? sender, RoutedEventArgs e)
        {
        }
        public void OnCbSuSZweitaccountClick(object? sender, RoutedEventArgs e)
        {
        }
    }
}
