name: Check for build errors
run-name: Building
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          cache: true
      - name: building release
        run: dotnet build -c RELEASE
