name: Gitea Actions Demo
run-name: Building and publishing
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: building release
        run: dotnet build -c RELEASE
      - name: publishing release
        run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
         - name: Use Go Action
         id: use-go-action
         uses: actions/release-action@main
         with:
           files: |-
             publish/win-x64/**
           api_key: '${{secrets.RELEASE_TOKEN}}'